trigger:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: terraform-pipeline
      type: Git
      name: terraform-pipeline
      ref: master

variables:
  - group: "TFE Variable Group"

pool:
  vmImage: "ubuntu-latest"

extends:
  template: pipeline/tfe-run-template.yml@terraform-pipeline
  parameters:
    isSpeculativePlan: False
    # terraformWorkingDirectory: ''
