# trigger:
#   branches:
#     include: 
#       - feature/*
trigger: none
pr:
 branches:
  include:
    - master

resources:
  repositories:
    - repository: terraform-pipeline
      type: Git
      name: eminently-suitable-kingfish/terraform-pipeline
      ref: master

variables:
  - group: 'TFE Variable Group'

extends:
  template: pipeline/tfe-run-template.yml@terraform-pipeline
  parameters:
    isSpeculativePlan: True
    # tfeTokenParam: $(tfeToken)
    # tfeWorkspaceName: "ado-demo"
    # terraformWorkingDirectory: ''
