trigger: none
pr: none

resources:
  repositories:
    - repository: terraform-pipeline
      type: Git
      name: terraform-tfe-ado/terraform-pipeline
      ref: master

variables:
  - group: "TFE Variable Group"

pool:
  vmImage: "ubuntu-latest"

extends:
  template: pipeline/tfe-destroy-template.yml@terraform-pipeline
  parameters:
    isSpeculativePlan: False
