trigger:
  - master

resources:
  repositories:
    - repository: terraform-pipeline
      type: Git
      name: surely-fine-humpback/terraform-pipeline
      ref: master

extends:
  template: pipeline/tfe-run-template.yml@terraform-pipeline
  parameters:
    isSpeculativePlan: False
    # terraformWorkingDirectory: ''
